### ISSUE TITLE
I need help :/

### ISSUE THREAD

**Issue by Lukour** [aeriie/spotify-playlist-updater#1]
Hi Aeriie,

I got sent your spotify playlist updater because I really have been struggling with bots. Every time I update my playlist, 5 min goes by and my name, cover and description is removed from the playlist. It is really sad as it is growing a lot in followers recently. The thing is.. I could really use your help, getting the code installed and activated. I have tried your tutorial but I really don't have the skills for it. Also I don't even know what the program is or what it does. Can you somehow help me? I really want my playlist to work... I was thinking maybe if you had 5-10 min, we could chat over discord. If you want payment I don't blame you

Lucas.

**Comment by aeriie** [comment]
Hey Lukor- I know I'm extremely late to this, but I'd be happy to help if you're still having issues or need help rebuilding your fanbase after all of that. Feel free to message me on discord- my username is .aeriie
