### ISSUE TITLE
Help with the Spotify app! :) 

### ISSUE THREAD

**Issue by arilefff** [aeriie/spotify-playlist-updater#2]
Hey Aeriie, 

I landed here from Spotify Community. I'm a Spotify user who's having trouble with his playlists being reported. I tried to do everything you said on to guide to set up the Playlist Updater but I'm absolutely no expert in coding and I probably did something wrong because the program is not working. How can we get in contact so I can ask you some fast questions in order to solve my issues? Thank you!

**Comment by aeriie** [comment]
I apologize for the delay in my response! I'd be happy to help if this is something you're still wanting help getting setup. Please don't hesitate to email me at [autumntillman0@gmail.com](mailto:autumntillman0@gmail.com).
