### ISSUE TITLE
Enter the URL you were redirected to

### ISSUE THREAD

**Issue by Fladoss** [aeriie/spotify-playlist-updater#3]
Hey! Got a problem.
When running a code I'm getting this:
`Starting Playlist updater`
`Enter the URL you were redirected to:`

It redirects to `https://vladprokopov26.wixsite.com/spotifyapi?code=AQCBrGH_MQAc2TsyNIQiXRtD1k7rGGSkLlxQFFWNoQ0_GtHt6DPCGvIgYGcyO9lTWB1xjzGrgPyDd3tKCB85xsHHHf_G3DnZWNOJ5d7Z_SZ2FajUgQ_yivneLKwsU4Ssu68YDrnX_CysKf_cHko-HDfBfiFaXasPXYlrPE8hvzGuWteFwXD1RrdXK_mZGj0_IJWMFgKmvoKH8EZ3phmKDgYzemYtCarFc07z_ADlCLy9VKxCNaez37q58w`

If I put it, it returns the error:
[traceback.txt](https://github.com/aeriie/spotify-playlist-updater/files/9064677/traceback.txt)

If I run again and put my WIX Site `(https://vladprokopov26.wixsite.com/spotifyapi)` here, it asks again:
`Enter the URL you were redirected to:`

If I put my WIX Site here again, it returns absolutely the same error.

It asks for redirected URL twice. If I put anything that doesn't equals `redirect_uri` which is `https://vladprokopov26.wixsite.com/spotifyapi`, it returns same error.

If I just press Enter two times it returns the same error...

Not sure what the problem is. I'm authorized in Spotify with my name, the client it and secret are right. I checked everything. Installed everything stated.

Mine script derictory:
`C:\Users\Aberdin\SpotifyAPI\Playlist Script`

**Comment by aeriie** [comment]
I know I'm a bit late to this, but it sounds like your site API token isn't setup properly. You'll want to doublecheck your Wix site settings to resolve this. Please don't hesitate to email me at autumntillman0@gmail.com if you would like me to help double check for you. 

Closing issue- not related to code
